### ISSUE TITLE
Cannot load plugins compiled from typescript

### ISSUE THREAD

**Issue by crystalfp** [slevey087/plugin-please#2]
I'm trying to write my plugins using typescript and compile them for `plugin-please`.
Unfortunately, they cannot be loaded for one thing I don't understand. The compiled js ends with that line (NoneReaderPlugin is the plugin function):
```
exports.NoneReaderPlugin = NoneReaderPlugin;
```
This gives the following error during loading:
```
D:\Projects\node_modules\plugin-please\src\plugins.js:45
        Object.assign(this, module(context || {}), { active: false })
                            ^

TypeError: module is not a function
    at new _Plugin (D:\Projects\node_modules\plugin-please\src\plugins.js:45:29)
    at Object.import (D:\Projects\node_modules\plugin-please\src\manager.js:61:19)
    at files.forEach.file (D:\Projects\node_modules\plugin-please\src\manager.js:75:48)
    at Array.forEach (<anonymous>)
    at Function.importAll (D:\Projects\node_modules\plugin-please\src\manager.js:75:15)
    at new PluginManager (D:\Projects\server\PluginManager.js:17:28)
    at Object.<anonymous> (D:\Projects\server\server.js:18:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
Instead changing this line to the equivalent:
```
module.exports = NoneReaderPlugin;
```
Works. But for me the two lines are equivalent.
Help!
mario

**Comment by crystalfp** [comment]
Nevermind. Workaround found. Simply end the plugin's typescript source with:
```
module.exports = NoneReaderPlugin;
```
Not elegant, but problem solved.
Thanks again for this module!
mario
